//! Shared data types for the Context-Store pipeline.

use serde::{Deserialize, Serialize};

/// An event generated by a [`ContextExtractor`] when the user switches focus to a new window.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowEvent {
    /// Name of the application (e.g. "Firefox", "Zed").
    pub app_name: String,
    /// Title of the focused window.
    pub window_title: String,
    /// Payload: either extracted text, or a signal that vision encoding is needed.
    pub content: WindowContent,
}

/// The content payload of a [`WindowEvent`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum WindowContent {
    /// Human-readable text extracted from the accessibility tree.
    Text(String),
    /// No text was found — the pipeline should fall back to a screenshot and vision encoding.
    ImageRequired,
    /// Encoded PNG screenshot bytes of the focused window.
    Screenshot(Vec<u8>),
}

/// A single result returned by the KNN search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextChunk {
    /// The extracted text (reserved for future use; currently `None`).
    pub text: Option<String>,
    /// Associated metadata from the SQLite `context_events` table.
    pub metadata: SourceMetadata,
    /// Cosine similarity score between the query embedding and this chunk.
    pub score: f32,
}

/// Metadata for a window-focus event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SourceMetadata {
    /// Primary key in the `context_events` table.
    pub id: i64,
    /// Application name.
    pub app_name: String,
    /// Window title.
    pub window_title: String,
    /// Unix timestamp (ms) when the event was first recorded.
    pub start_time: i64,
    /// Unix timestamp (ms) of the last dedup-triggered end_time update.
    pub end_time: Option<i64>,
    /// Either `"text"` or `"vision"`.
    pub source_type: String,
    /// Code file path if detected, e.g. "main.rs"
    pub code_file: Option<String>,
    /// Project name if detected, e.g. "aleph"
    pub code_project: Option<String>,
    /// Git branch if detected, e.g. "main"
    pub code_branch: Option<String>,
}

/// Request body for `POST /query`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryRequest {
    /// Natural-language question.
    pub question: String,
    /// Number of results to return (default 5).
    #[serde(default = "default_top_k")]
    pub top_k: usize,
}

/// Response body for `POST /query`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueryResponse {
    /// Ranked list of context chunks.
    pub context: Vec<ContextChunk>,
    /// Deduplicated list of source metadata (same order as `context`).
    pub sources: Vec<SourceMetadata>,
}

fn default_top_k() -> usize {
    5
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AskRequest {
    pub question: String,
    #[serde(default = "default_top_k")]
    pub top_k: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AskResponse {
    pub answer: String,
    pub sources: Vec<SourceMetadata>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CaptureStatus {
    pub enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScreenshotResponse {
    pub id: i64,
    pub png_base64: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailySummaryResponse {
    pub date: String,
    pub summary: String,
}

// ---------------------------------------------------------------------------
// Dashboard / Stats models
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OverviewStats {
    pub total_events: i64,
    pub total_apps: i64,
    pub total_tracked_hours: f64,
    pub today_events: i64,
    pub most_used_app: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HourlyStat {
    pub hour: i64,
    pub count: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DailyStat {
    pub date: String,
    pub count: i64,
    pub duration_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppStat {
    pub app_name: String,
    pub count: i64,
    pub duration_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowStat {
    pub app_name: String,
    pub window_title: String,
    pub count: i64,
    pub duration_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentEvent {
    pub id: i64,
    pub app_name: String,
    pub window_title: String,
    pub start_time: i64,
    pub end_time: Option<i64>,
    pub duration_ms: i64,
    pub source_type: String,
    pub category: Option<String>,
    pub code_file: Option<String>,
    pub code_project: Option<String>,
    pub code_branch: Option<String>,
}
